# Generated by Django 4.1.4 on 2023-03-13 11:13

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("attractive_text", models.TextField(default="Завлекающий текст")),
                (
                    "image_base",
                    models.ImageField(default="img/placeholder.png", upload_to="img"),
                ),
                ("main_text", models.TextField(default="Основной текст")),
                (
                    "article_inner_links",
                    django_mysql.models.ListTextField(
                        models.CharField(default="aaa", max_length=40),
                        default="",
                        size=100,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
