# Generated by Django 4.1.4 on 2023-12-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("popular_element", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="populararticle",
            options={"verbose_name_plural": "Элемет 'Популярные статьи'"},
        ),
    ]
