# Generated by Django 4.1.4 on 2024-01-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("popular_element", "0007_alter_populararticle_options_categoriestiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriestiles",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
    ]
