# Generated by Django 4.1.4 on 2023-12-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_text", models.TextField(max_length=255)),
                ("detailed_text", models.TextField(max_length=255)),
                ("type", models.IntegerField(default=1)),
                ("result", models.FloatField(default=0.0)),
            ],
        ),
    ]
