# Generated by Django 4.1.4 on 2023-12-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header_text", models.TextField(max_length=255)),
                ("detailed_text", models.TextField(max_length=255)),
                ("type", models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name="testprogress",
            name="detailed_text",
        ),
        migrations.RemoveField(
            model_name="testprogress",
            name="header_text",
        ),
        migrations.RemoveField(
            model_name="testprogress",
            name="type",
        ),
    ]
