# Generated by Django 4.1.4 on 2023-12-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0004_remove_accounttestprogress_tests_progress_and_more"),
        ("test_progress", "0002_test_remove_testprogress_detailed_text_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestProgress",
        ),
    ]
