# Generated by Django 4.1.4 on 2023-12-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0003_delete_testprogress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name_plural": "Тесты"},
        ),
    ]
