# Generated by Django 4.1.4 on 2023-12-02 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0004_alter_test_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={
                "verbose_name": "Тест (результаты)",
                "verbose_name_plural": "Тесты (результаты)",
            },
        ),
    ]
