# Generated by Django 4.1.4 on 2023-12-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0005_alter_test_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="marks",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="test",
            name="question",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
