# Generated by Django 4.1.4 on 2023-12-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0006_test_marks_test_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="header_text",
            field=models.CharField(max_length=255),
        ),
    ]
