# Generated by Django 4.1.4 on 2023-12-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0008_question_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_object_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_object",
                to="test_progress.testobject",
            ),
            preserve_default=False,
        ),
    ]
