# Generated by Django 4.1.4 on 2023-12-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0010_testanswer_alter_testobject_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "Вопрос (Выбор вариантов)",
                "verbose_name_plural": "Вопросы (Выбор вариантов)",
            },
        ),
    ]
