# Generated by Django 4.1.4 on 2023-12-17 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0011_alter_question_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={},
        ),
        migrations.RemoveField(
            model_name="test",
            name="detailed_text",
        ),
        migrations.RemoveField(
            model_name="test",
            name="header_text",
        ),
        migrations.RemoveField(
            model_name="test",
            name="marks",
        ),
        migrations.RemoveField(
            model_name="test",
            name="question",
        ),
        migrations.RemoveField(
            model_name="test",
            name="type",
        ),
    ]
