# Generated by Django 4.1.4 on 2023-12-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0013_delete_test_delete_testanswer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "Тест (Выбор вариантов)",
                "verbose_name_plural": "Тесты (Выбор вариантов)",
            },
        ),
        migrations.AlterModelOptions(
            name="testobject",
            options={},
        ),
    ]
