# Generated by Django 4.1.4 on 2023-12-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0014_alter_question_options_alter_testobject_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestObjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_type_title", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="testobject",
            name="test_type",
            field=models.ManyToManyField(to="test_progress.testobjecttype"),
        ),
    ]
