# Generated by Django 4.1.4 on 2023-12-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0016_testobject_test_max_result_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "3.2. Вариант ответа (Выбор вариантов)",
                "verbose_name_plural": "3.2. Вариант ответа (Выбор вариантов)",
            },
        ),
        migrations.AlterModelOptions(
            name="testobject",
            options={
                "verbose_name": "3.1. Тест (Выбор вариантов)",
                "verbose_name_plural": "3.1. Тесты (Выбор вариантов)",
            },
        ),
    ]
