# Generated by Django 4.1.4 on 2024-01-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0017_alter_question_options_alter_testobject_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testobject",
            name="test_object_name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
