# Generated by Django 4.1.5 on 2024-01-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0018_alter_testobject_test_object_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "verbose_name": "3.3. Вариант ответа (Выбор вариантов)",
                "verbose_name_plural": "3.3. Вариант ответа (Выбор вариантов)",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "3.2. Вопрос (Выбор вариантов)",
                "verbose_name_plural": "3.2. Вопросы (Выбор вариантов)",
            },
        ),
    ]
