# Generated by Django 4.1.4 on 2024-02-24 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0024_delete_accounttestprogress"),
        ("test_progress", "0019_alter_answer_options_alter_question_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTestProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_status", models.IntegerField(default=0)),
                ("result", models.IntegerField(default=-1)),
                (
                    "result_detailed",
                    models.JSONField(default={"answers": {}, "total_points": 0}),
                ),
                (
                    "attemp_started",
                    models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
                ),
                (
                    "attemp_finished",
                    models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
                ),
                ("profile", models.ManyToManyField(to="account_page.profile")),
                ("tests", models.ManyToManyField(to="test_progress.testobject")),
            ],
            options={
                "verbose_name": "Связка 'Профиль' - 'Тест'",
                "verbose_name_plural": "Связки 'Профиль' - 'Тест'",
            },
        ),
    ]
