# Generated by Django 4.1.4 on 2024-02-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0020_accounttestprogress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounttestprogress",
            options={
                "verbose_name": "3.1. Назначение теста",
                "verbose_name_plural": "3.1. Назначения теста",
            },
        ),
        migrations.AlterModelOptions(
            name="answer",
            options={
                "verbose_name": "3.2.2. Вариант ответа (Выбор вариантов)",
                "verbose_name_plural": "3.2.2. Варианты ответа (Выбор вариантов)",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "3.2.1. Вопрос (Выбор вариантов)",
                "verbose_name_plural": "3.2.1. Вопросы (Выбор вариантов)",
            },
        ),
        migrations.AlterModelOptions(
            name="testobject",
            options={
                "verbose_name": "3.2. Тест (Выбор вариантов)",
                "verbose_name_plural": "3.2. Тесты (Выбор вариантов)",
            },
        ),
    ]
