# Generated by Django 4.1.4 on 2023-03-13 11:13

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("attractive_text", models.TextField(default="Завлекающий текст")),
                (
                    "image_base",
                    models.ImageField(default="img/placeholder.png", upload_to="img"),
                ),
                ("main_text", models.TextField(default="Основной текст")),
                (
                    "main_text_headers_list",
                    django_mysql.models.ListTextField(
                        models.CharField(default="", max_length=40),
                        default=None,
                        size=100,
                    ),
                ),
                (
                    "main_text_headers_list_keys",
                    models.CharField(default=" ", max_length=200),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author", models.CharField(max_length=60)),
                ("body", models.TextField()),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.article",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.ManyToManyField(
                related_name="articles", to="articles.category"
            ),
        ),
        # migrations.AddField(
        #     model_name="article",
        #     name="quizzes",
        #     field=models.ManyToManyField(
        #         blank=True, default="", related_name="quizzes", to="quiz.quizpick4"
        #     ),
        # ),
    ]
