# Generated by Django 4.1.4 on 2023-03-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="color",
            field=models.CharField(default="#ffffff", max_length=7),
        ),
    ]
