# Generated by Django 4.1.4 on 2023-03-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_category_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image_base",
            field=models.ImageField(default="img/placeholder_6.png", upload_to="img"),
        ),
    ]
