# Generated by Django 4.1.4 on 2023-11-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_alter_article_image_base"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="flag_article_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
