# Generated by Django 4.1.4 on 2023-12-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_image_base"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name_plural": "Статьи"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Категории"},
        ),
    ]
