# Generated by Django 4.1.4 on 2023-12-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0005_alter_article_options_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Статья", "verbose_name_plural": "Статьи"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
    ]
