# Generated by Django 4.1.4 on 2024-01-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0007_alter_article_options_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-title"],
                "verbose_name": "2.1. Статья",
                "verbose_name_plural": "2.1. Статьи",
            },
        ),
    ]
