# Generated by Django 4.1.4 on 2023-12-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutinfo",
            options={
                "verbose_name": "Главный текст",
                "verbose_name_plural": "Главный текст",
            },
        ),
    ]
