# Generated by Django 4.1.5 on 2024-01-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_aboutinfo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutinfo",
            options={
                "verbose_name": "4.1 Главный текст",
                "verbose_name_plural": "4.1 Главный текст",
            },
        ),
    ]
