# Generated by Django 4.1.4 on 2024-02-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_aboutinfo_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aboutinfo",
            options={
                "verbose_name": "4.1. Текст на главном постере",
                "verbose_name_plural": "4.1. Текст на главном постере",
            },
        ),
    ]
