# Generated by Django 4.1.4 on 2023-12-02 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0001_initial"),
        ("account_page", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTestProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account_page.profile",
                    ),
                ),
                ("tests", models.ManyToManyField(to="test_progress.testprogress")),
            ],
        ),
    ]
