# Generated by Django 4.1.4 on 2023-12-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_progress", "0002_test_remove_testprogress_detailed_text_and_more"),
        ("account_page", "0002_accounttestprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttestprogress",
            name="tests_progress",
            field=models.ManyToManyField(to="test_progress.testprogress"),
        ),
        migrations.AlterField(
            model_name="accounttestprogress",
            name="tests",
            field=models.ManyToManyField(to="test_progress.test"),
        ),
    ]
