# Generated by Django 4.1.4 on 2023-12-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0003_accounttestprogress_tests_progress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounttestprogress",
            name="tests_progress",
        ),
        migrations.AddField(
            model_name="accounttestprogress",
            name="current_status",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="accounttestprogress",
            name="result",
            field=models.FloatField(default=0.0),
        ),
    ]
