# Generated by Django 4.1.4 on 2023-12-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0004_remove_accounttestprogress_tests_progress_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounttestprogress",
            name="profile",
        ),
        migrations.AddField(
            model_name="accounttestprogress",
            name="profile",
            field=models.ManyToManyField(to="account_page.profile"),
        ),
    ]
