# Generated by Django 4.1.4 on 2023-12-02 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0006_alter_profile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Профили"},
        ),
    ]
