# Generated by Django 4.1.4 on 2023-12-02 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0008_alter_accounttestprogress_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounttestprogress",
            options={
                "verbose_name": "Связка 'Профиль' - 'Тест'",
                "verbose_name_plural": "Связки 'Профиль' - 'Тест'",
            },
        ),
    ]
