# Generated by Django 4.1.5 on 2024-01-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0017_alter_accounttestprogress_result_detailed"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttestprogress",
            name="attemp_finished",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="accounttestprogress",
            name="attemp_started",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
