# Generated by Django 4.1.5 on 2024-01-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0018_accounttestprogress_attemp_finished_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttestprogress",
            name="attemp_finished",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="accounttestprogress",
            name="attemp_started",
            field=models.DateTimeField(null=True),
        ),
    ]
