# Generated by Django 4.1.5 on 2024-01-13 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0019_alter_accounttestprogress_attemp_finished_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttestprogress",
            name="attemp_finished",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="accounttestprogress",
            name="attemp_started",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
