# Generated by Django 4.1.5 on 2024-01-16 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0021_profile_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="is_admin",
        ),
    ]
