# Generated by Django 4.1.5 on 2024-01-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0022_remove_profile_is_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
