# Generated by Django 4.1.4 on 2024-02-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0024_delete_accounttestprogress"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "1.1. Профиль",
                "verbose_name_plural": "1.1. Профили",
            },
        ),
    ]
