# Generated by Django 4.1.4 on 2024-02-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0026_interfaceuserslist_interfacedownloaduserslist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interfaceuserslist",
            name="stored_file",
            field=models.FileField(
                default="files/users.xlsx", upload_to="static/files"
            ),
        ),
    ]
