# Generated by Django 4.1.4 on 2024-02-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0028_interfaceuserslist_last_used_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interfaceuserslist",
            name="last_used_by",
        ),
    ]
