# Generated by Django 4.1.4 on 2024-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_page", "0030_remove_interfaceuserslist_stored_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interfacedownloaduserslist",
            name="stored_file",
            field=models.FileField(default="files/users.xlsx", upload_to=""),
        ),
        migrations.AlterField(
            model_name="interfaceuploaduserslist",
            name="stored_file",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
